# Generated by Django 5.2.7 on 2025-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('MYR', 'MYR (RM)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('INR', 'INR (₹)')], default='MYR', max_length=3),
        ),
    ]
