# Generated by Django 5.2.7 on 2025-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0005_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('MYR', 'MYR (RM)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('INR', 'INR (₹)'), ('SGD', 'SGD ($)')], default='MYR', max_length=3),
        ),
    ]
